version: 0.0
os : linux
files:version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-node-app
    overwrite: yes

permissions:
  - object: /home/ubuntu/my-node-app
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: root

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 180
      runas: root
